services:
  crypto-p2p-trading-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    # restart: unless-stopped
    container_name: crypto-p2p-trading-app
    environment:
      - TZ=UTC
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/exchange?sslmode=disable
      - WALLET_SEED=your_secure_seed_phrase_here
      - RPC_URL=https://bsc-dataseed.binance.org/
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8000/api/pairs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exchange
    volumes:
      - ./pg_volume/volumes/postgres:/var/lib/postgresql/data # link container folder to host machine folder
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres

volumes:
  postgres_data:
