services:
  crypto-p2p-trading-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9010:8000"
    # restart: unless-stopped
    container_name: crypto-p2p-trading-app
    environment:
      - TZ=${TZ}
      - DATABASE_URL=${DATABASE_URL}
      - WALLET_SEED=${WALLET_SEED}
      - RPC_URL=${RPC_URL}
      - REQUIRED_CONFIRMATIONS=${REQUIRED_CONFIRMATIONS}
      - BLOCKCHAIN_DEBUG_MODE=${BLOCKCHAIN_DEBUG_MODE:-false}   # Use value from .env, default to false if not set
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8000/api/pairs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - crypto-trading-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data # ./pg_volume/volumes/postgres:/var/lib/postgresql/data # link container folder to host machine folder
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - crypto-trading-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - crypto-trading-network

volumes:
  postgres_data:

networks:
  crypto-trading-network:
    driver: bridge
    name: crypto-trading-network
